sudo: required
dist: trusty
language: php
php:
  - "7.0"
  - "7.1"
  - "7.2"

services:
  - docker

install:
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
  - cat Dockerfile
  - docker-compose build --build-arg PHP_VERSION=${TRAVIS_PHP_VERSION}

script:
  - mkdir -p build/logs
  - chmod 777 -R build/logs
  - docker-compose up --exit-code-from php
  - ls -l build/logs

after_script:
  - travis_retry php vendor/bin/php-coveralls -v --root_dir ./
