sudo: required
dist: trusty
language: php
php:
  - "5.6"
  - "7.0"

services:
  - docker

install:
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
  - cat Dockerfile
  - docker-compose build --build-arg PHP_VERSION=${TRAVIS_PHP_VERSION}

script:
  - docker-compose up --exit-code-from php
