version: '3'

services:
    php:
        container_name: php_trustnosql
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/code
        working_dir: /code
        command: bash -c "composer update --prefer-source --no-interaction && php ./vendor/bin/phpunit --coverage-text --verbose"
        depends_on:
          - mongodb

    mongodb:
        container_name: mongodb_trustnosql
        image: mongo
        logging:
            driver: none
        environment:
            MONGO_INITDB_ROOT_USERNAME: trustnosql
            MONGO_INITDB_ROOT_PASSWORD: trustnosql
            MONGO_INITDB_DATABASE: trustnosql
